environment: dev

dev:
  flask:
    host: "0.0.0.0"
    port: 5000
    debug: true

  logging:
    enabled: true 
    logfile: "access" 
    level: "INFO" 

  endpoints:
    - path: "/"
      method: ["GET"]
      response: 
        type: "raw"
        value: "Welocome to AutoAPI"

    - path: "/status"
      method: ["GET"]
      response:
        type: "raw"
        value: "OK" 

    - path: "/books"
      routes: 
        - path: "/" 
          method: ["GET"]
          response: 
            type: "python"
            value: "tests.book_api"
            function: "get_books" 

        - path: "/add"
          method: ["POST"]
          response: 
            type: "python"
            value: "tests.book_api"
            function: "post_book"

        - path: "/update/<id>"
          method: ["PUT"]
          response: 
            type: "python"
            value: "tests.book_api"
            function: "update_book"

        - path: "/delete/<id>"
          method: ["DELETE"]
          response: 
            type: "python"
            value: "tests.book_api"
            function: "delete_book" 
